### PR TITLE
add Lesley's details

### PR DESCRIPTION
**Pull request by jonah-sullivan**

### CODE REVIEW

**Comment by jonah-sullivan** [comment]
Hopefully the speaker images show up this time, please have a look to see if they do.

**Comment by jonah-sullivan** [comment]
@om-henners, please merge this pull request. Also, please check to see if the image links are working...I think they are.

**Review by EdwinLiavaa — APPROVED** [review]

**Comment by EdwinLiavaa** [comment]
merged!

**Comment by jonah-sullivan** [comment]
Thanks @FidelChe. The speaker photos are finally showing up.

**Comment by EdwinLiavaa** [comment]
Yes, tonnes of thanks @jonah-sullivan

**Pull request merged**
