### PR TITLE
Added table with | speaker name | title |

### LINKED ISSUE #114: Tabular view of keynote speakers
It would be nice to have a table at the top of the programme page to see all of the information at once.

I'll work on it later today.

### PR DESCRIPTION
**Pull request by jonah-sullivan**
Closes #114

### CODE REVIEW

**Comment by EdwinLiavaa** [comment]
merged!

**Comment by jonah-sullivan** [comment]
What a letdown. I thought I could use markdown to make a table and it totally didn't work.

@FidelChe , do you know how to do it?

**Comment by EdwinLiavaa** [comment]
Am busy at the moment but will have time tonight...cheers

**Comment by jonah-sullivan** [comment]
@FidelChe , could you please revert this?

**Comment by EdwinLiavaa** [comment]
Fixed :)

**Comment by jonah-sullivan** [comment]
Thanks @FidelChe, it looks really good.

I thought it would be an easy bit to add a markdown table, but I guess if the file extension is .html then you have to use html formatting.

**Comment by EdwinLiavaa** [comment]
Yes...html->html

**Pull request merged**
