### PR TITLE
The Perth point on the map now links to the Perth hub page

### PR DESCRIPTION
**Pull request by keithamoss**

### CODE REVIEW

**Comment by jonah-sullivan** [comment]
The page looks great.

The signup link doesn't work.

There's a MailChimp mailing list for the conference in general, but not for each hub. I think perth@osgeo-oceania.org is being provisioned.

There is an email announcement going out this week announcing the hubs, how do you feel about the announcement highlighting this site as an example of the grass-roots nature of the conference hubs?

**Comment by keithamoss** [comment]
Re the sign up link - We're working on a Google Form for a 'Hold the date' campaign that this'll link to.

We've got perth-hub@foss4g-oceania.org up and running now and are pushing folks there for now.

I'm happy for our page to get highlighted. Ping @johnwbryant. In that case, I'll just push a PR to make that 'Sign up' button point at our email address until the form is ready.

**Comment by jonah-sullivan** [comment]
That's great!

Good going. I'll put a link into the email blast.

**Comment by johnwbryant** [comment]
Sounds great! I will have to get in there and take my name off the
conference content section :P

We should be able to get a first pass of the sign up form done in the next
couple of days too. Will update the page when that's good to go.

**Comment by EdwinLiavaa** [comment]
Looking great team...cheers!

**Pull request merged**
