### PR TITLE
changed mailchimp signup form style to "horizontal"

### PR DESCRIPTION
**Pull request by jonah-sullivan**

### CODE REVIEW

**Comment by EdwinLiavaa** [comment]
mailchimp signup merge committed

**Comment by jonah-sullivan** [comment]
Thanks, the horizontal style looks better.

**Comment by EdwinLiavaa** [comment]
Yes :)

**Comment by adamsteer** [comment]
quick comment - it's not clear at all what people are signing up for here. This process should somewhere explain:

- what communications a person should expect (related to this conference only, or for this and future conferences)
- what we do with data collected (ie your e-mail address will be retained by OSGeo Oceania for FOSS4G SotM conference communication purposes)

thnx, and the website is coming together nicely. Hope the experience of building it is going well ;)

**Comment by EdwinLiavaa** [comment]
+1 Agree

**Comment by EdwinLiavaa** [comment]
Hi Jonah,

Just following up on Adam's input. What is the signing up for? Is it for
registering interest in participating in the conference?

cheers,

Edwin

**Comment by EdwinLiavaa** [comment]
Have changed it to "Sign up for event updates...Get updates in time and
more."
cheers,

Edwin

**Pull request merged**
