### PR TITLE
add link to cairns hub website

### PR DESCRIPTION
**Pull request by jonah-sullivan**

### CODE REVIEW

**Comment by jonah-sullivan** [comment]
@FidelChe , could you please merge this one and #80 ? They should be straightforward.

**Comment by jonah-sullivan** [comment]
Closes #77

**Comment by EdwinLiavaa** [comment]
merged!

**Comment by jonah-sullivan** [comment]
Thanks for clearing up all of these pull requests.

The website is looking really good!

**Comment by EdwinLiavaa** [comment]
Totally awesome...cheers!

**Pull request merged**
