### PR TITLE
Update nav.html

### PR DESCRIPTION
**Pull request by EdwinLiavaa**

### CODE REVIEW

**Comment by jonah-sullivan** [comment]
@FidelChe , you have write access don't you (I don't).

**Comment by EdwinLiavaa** [comment]
Hi Jonah, I've made some pull requests but seems to no avail.

**Comment by jonah-sullivan** [comment]
I messaged @adamsteer and @alexgleith  to give you write access, but I don't think they're online just now.

Thanks for putting in the effort on this site. Its starting to look really good.

**Comment by EdwinLiavaa** [comment]
Tonnes of thanks Jonah...cheers!

**Comment by alexgleith** [comment]
You should have access now, @FidelChe

**Comment by EdwinLiavaa** [comment]
Tonnes of thanks Alex

**Pull request closed without merging**
