### PR TITLE
suva hub updates

### PR DESCRIPTION
**Pull request by nemaiakoto**
created suva hub index.md and updated link from home page.

### CODE REVIEW

**Comment by EdwinLiavaa** [comment]
Merged!

**Comment by jonah-sullivan** [comment]
Yeah @nemaiakoto, looks good. I can't see the graphic hosted on ibb.co on my work laptop because the corporate firewall blocks that website, but ti should work for most people. You can save the graphic in this folder if you want to:
https://github.com/foss4g-oceania/foss4g-sotm-oceania-2020/tree/master/img

**Comment by nemaiakoto** [comment]
@FidelChe thanks!

@jonah-sullivan via upload file? its saying i need push access to repository to upload any file.

**Comment by jonah-sullivan** [comment]
You can put the graphic into your fork, and then do a pull request.

You'll also have to change the graphic link in the markdown document in your fork.

**Pull request merged**
