### PR TITLE
remove reference to slack channel

### PR DESCRIPTION
**Pull request by jonah-sullivan**

### CODE REVIEW

**Comment by jonah-sullivan** [comment]
@FidelChe, I think I might have broken something with this pull request. There is a notification that there are conflicts that must be resolved. Do you know how to fix that, 'cause I don't.

**Comment by EdwinLiavaa** [comment]
Fixed

**Comment by jonah-sullivan** [comment]
Thanks Edwin. Did you have to do anything fancy? Was it a warning or an error, or something else?

**Comment by EdwinLiavaa** [comment]
Nothing fancy, apparently there was a conflict between your version and the
master. I did a lazy fix by editing what you wanted and just closed your
pull request.

**Comment by jonah-sullivan** [comment]
I think the problem was that I did several edits and several pull requests.

I also made another pull request to add a page for the Canberra hub. It's PR number 35. 

https://github.com/foss4g-oceania/foss4g-sotm-oceania-2020/pull/35

Can that one be merged?

**Comment by EdwinLiavaa** [comment]
Please try doing the same pull request now

**Comment by jonah-sullivan** [comment]
Done 
https://github.com/foss4g-oceania/foss4g-sotm-oceania-2020/pull/37

**Comment by EdwinLiavaa** [comment]
Look good :)

**Pull request closed without merging**
