### PR TITLE
reformat Canberra hub

### PR DESCRIPTION
**Pull request by jonah-sullivan**

### CODE REVIEW

**Comment by jonah-sullivan** [comment]
@om-henners, this says it has conflicts, but it seems ok to me.

Could you please merge it?

**Comment by om-henners** [comment]
@jonah-sullivan no problem - I'll take a look

**Comment by om-henners** [comment]
It's been merged. Let me know if there's any issues!

**Comment by jonah-sullivan** [comment]
Thanks Henry.

**Pull request closed without merging**
